version: '3'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lancer
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
